version: 0.2

env:
  variables:
    ECR_REPOSITORY: "tool-go"

phases:
  pre_build:
    commands:
      - echo "Setting varables"
      - export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | awk -F ':' '{print $5}')
      - export ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr;${AWS_REGION}.amazonaws.com"
      - export ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPOSITORY}:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
      - echo "Logging into ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t "${ECR_IMAGE_URI}" .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images to ECR...
      - docker push "${ECR_IMAGE_URI}"
      - echo Writing image definitions file...
      - sed -i "s|<ECR_IMAGE_URI>|$<ECR_IMAGE_URI>|g" taskDefinition.json
      - aws ecs register-task-definition --cli-input-json file://taskDefinition.json
artifacts:
  files:
    - taskDefinition.json
