version: 0.2

env:
  variables:
    ECR_REPOSITORY: "tool-go" # Nome do repositório no ECR
    AWS_DEFAULT_REGION: "us-east-2" # Sua região AWS

phases:
  pre_build:
    commands:
      - echo "Setting variables..."
      - export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | awk -F ':' '{print $5}')
      - export ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - export ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPOSITORY}:latest"
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_MAIN_URI

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t "${ECR_IMAGE_URI}" .

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image to ECR..."
      - docker push "${ECR_IMAGE_URI}"
      - printf '[{"name":"tool_go","imageUri":"%s"}]' $ECR_IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
